apiVersion: xl/v2
kind: Blueprint

metadata:
  name: Define a Kubernetes application
  description: |
    This blueprint defines an application that can be deployed to Kubernetes
  author: XebiaLabs
  version: 2.0
  instructions: Read xebialabs/USAGE-kubernetes-application.md to learn how to use this blueprint.

spec:
  parameters:
  - name: KubernetesApplicationName
    type: Input
    prompt: "What is the name of the application that you want to deploy?"
    default: nginx

  - name: KubernetesDeploymentPackageVersion
    type: Input
    prompt: "What is the version of the application that you want to deploy?"
    default: latest

  - name: Namespace
    type: Input
    prompt: "Name of new namespace that will be created:"
    default: default

  - name: NamespaceTag
    type: Input
    value: kubernetes-namespace

  files:
  # XebiaLabs
  - path: xebialabs/USAGE-kubernetes-application.md
  - path: xebialabs/kubernetes-application.yaml.tmpl
  # Kubernetes
  - path: kubernetes/nginx-deployment.yaml.tmpl
  - path: kubernetes/nginx-service.yaml.tmpl
