apiVersion: xl-cli/v1beta1
kind: Blueprint
metadata:
  projectName: AWS-Datalake 
  description: |
    The blueprint deploys a data lake architecture to AWS using CloudFormation.
    XL deploy does the provisioning and deployment, while XL release orchestrates everything.
    Refer https://docs.aws.amazon.com/solutions/latest/data-lake-solution
  author: XebiaLabs
  version: 1.0
spec:
- name: S3BucketName
  description: The S3 bucket name to use for CloudFormation templates
  type: Input
- name: AdministratorName
  description: Name of the Data Lake administrator
  type: Input
- name: AdministratorEmail
  description: A valid Email address for Data Lake administrator
  type: Input
- name: CognitoDomain
  description: Prefixed domain names can only contain lower-case letters, numbers, and hyphens
  type: Input
- name: AWSAccessKey
  type: Input
  secret: true
  value: !fn aws.credentials().AccessKeyID
- name: AWSAccessSecret
  type: Input
  secret: true
  value: !fn aws.credentials().SecretAccessKey
- name: AWSRegion
  type: Select
  options:
    - !fn aws.regions(lambda)
  default: !fn aws.regions(lambda)[0]