apiVersion: xl-cli/v1beta1
kind: Blueprint

metadata:
  projectName: AWS-Microservice-EKS-with-JHipster
  description: |
    The blueprint deploys an e-commerce microservice application to AWS EKS.
    XL deploy does the provisioning and deployment, while XL release orchestrates everything.
  author: XebiaLabs
  version: 1.0

spec:
# General variables
- name: AppName
  type: Input
  description: Enter name of the application

# AWS specific variables
- name: AWSAccessKey
  type: Input
  secret: true
  value: !fn aws.credentials().AccessKeyID
- name: AWSAccessSecret
  type: Input
  secret: true
  value: !fn aws.credentials().SecretAccessKey
- name: AWSRegion #options are set manually because EKS service is not registered within AWS GO SDK
  type: Select
  description: Select AWS region
  options:
    - eu-west-1
    - us-east-1
    - us-west-2
- name: ProvisionCluster
  type: Confirm
  description: Provision a new AWS EKS cluster?
- name: ClusterName
  type: Input
  description: AWS EKS cluster name to create/use
- name: ClusterEndpoint
  type: Input
  dependsOnFalse: ProvisionCluster
  description: URL for RESTful interface provided by API Server, example https://cluster1.k8s.abc.org
- name: UseExistingNamespace
  type: Confirm
  dependsOnFalse: ProvisionCluster
  description: Use an existing K8s namespace?
- name: Namespace
  type: Input
  description: Enter the name of the namespace to create/use
  default: default

# XLD/XLR specific variables
- name: XLDServerURL
  type: Input
  default: http://xl-deploy:4516
  description: XL-Deploy URL
- name: XLDUsername
  type: Input
  default: admin
  description: XL-Deploy user name
- name: XLDPassword
  type: Input
  secret: true
  description: XL-Deploy user password
- name: XLRUsername
  type: Input
  default: admin
  description: XL-Release user name
- name: XLRPassword
  type: Input
  secret: true
  description: XL-Release user password